name: zhifubao
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_swiper: ^1.1.6

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_webview_plugin: ^0.3.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/swiper1.jpg
    - images/swiper2.jpg
    - images/swiper3.jpg

    - images/caifu1.jpg
    - images/caifu2.jpg
    - images/caifu3.jpg

    - images/choujiang.png
    - images/choujiang2.png
    - images/ditu.png
    - images/xinwen.png
    - images/shucai.png
    - images/yiyonxiang.png
    - images/huabei.png
    - images/shangjia.png
    - images/tixing.png
    - images/wangshandai.png
    - images/mayi.png
    - images/xianghu.png
    - images/xingyundou.png
    - images/daren.png
    - images/meinv.png

    - images/huiyuan.png
    - images/shangjia2.png
    - images/zhangdan.png
    - images/zongzichan.png
    - images/yue.png
    - images/yueb.png
    - images/huabei2.png
    - images/yulibao.png
    - images/yinhangka.png
    - images/zhimaxinyon.png
    - images/baoxian.png
    - images/xhhy.png
    - images/jiebei.png
    - images/wsyh.png
    - images/gongyi.png
    - images/kefu.png
